name: g2-csdpc
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.8
  - ca-certificates=2026.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - exceptiongroup=1.2.2
  - h2=4.1.0
  - h5py=3.11.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=78.3
  - idna=3.10
  - iniconfig=2.0.0
  - joblib=1.4.2
  - keyutils=1.6.3
  - krb5=1.22.2
  - ld_impl_linux-64=2.46.1
  - libaec=1.1.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.22.0
  - libedit=3.1.20250104
  - libev=4.33
  - libffi=3.7.0
  - libgcc=16.2.0
  - libgcc-ng=16.2.0
  - libgfortran=16.2.0
  - libgfortran-ng=16.2.0
  - libgfortran5=16.2.0
  - libgomp=16.2.0
  - liblapack=3.9.0
  - liblzma=5.8.3
  - liblzma-devel=5.8.3
  - libnghttp2=1.68.1
  - libnsl=2.0.1
  - libopenblas=0.3.25
  - libpsl=0.23.1
  - libsqlite=3.53.4
  - libssh2=1.11.1
  - libstdcxx=16.2.0
  - libstdcxx-ng=16.2.0
  - libuuid=2.42.2
  - libxcrypt=4.4.38
  - libzlib=1.3.2
  - ncurses=6.6
  - numpy=1.24.3
  - openssl=3.6.4
  - packaging=26.2
  - pip=24.3.1
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - pooch=1.8.2
  - pycparser=2.22
  - pysocks=1.7.1
  - pytest=8.3.4
  - python=3.8.20
  - python_abi=3.8
  - pyyaml=6.0.2
  - readline=8.3
  - requests=2.32.3
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - setuptools=75.3.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tomli=2.0.2
  - urllib3=2.2.3
  - wheel=0.45.1
  - xz=5.8.3
  - xz-gpl-tools=5.8.3
  - xz-tools=5.8.3
  - yaml=0.2.5
  - zstandard=0.19.0
  - zstd=1.5.7

